version: '3'
services:
  pg:
    image: postgres
    ports:
    - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 
      POSTGRES_DB: ex3
    volumes:
    - ./ex3.sql:/docker-entrypoint-initdb.d/init.sql
    command: postgres -c max_prepared_transactions=10
